#!/usr/bin/env python3
"""slice_grid.py — Slice a 3x3 (or NxM) storyboard grid image into individual cut frames.

Splits multi-panel storyboard grid images generated by Google Flow into numbered
sequential frames (e.g. frame_01.png ~ frame_09.png) suitable for animatic assembly,
frame interpolation, or scene-by-scene editing.

Usage:
  python3 slice_grid.py --input grid.png --output ./frames --rows 3 --cols 3
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from PIL import Image


def slice_grid(
    image_path: Path,
    output_dir: Path,
    rows: int = 3,
    cols: int = 3,
    prefix: str = "frame",
) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    img = Image.open(image_path)
    w, h = img.size
    cell_w = w // cols
    cell_h = h // rows

    saved_paths = []
    idx = 1
    for r in range(rows):
        for c in range(cols):
            left = c * cell_w
            top = r * cell_h
            right = left + cell_w
            bottom = top + cell_h
            cell = img.crop((left, top, right, bottom))
            out_path = output_dir / f"{prefix}_{idx:02d}.png"
            cell.save(out_path)
            saved_paths.append(out_path)
            idx += 1

    return saved_paths


def main() -> None:
    ap = argparse.ArgumentParser(description="Slice storyboard grid into sequential frames")
    ap.add_argument("--input", "-i", required=True, help="Input grid image path")
    ap.add_argument("--output", "-o", required=True, help="Output directory for sliced frames")
    ap.add_argument("--rows", "-r", type=int, default=3, help="Grid rows (default: 3)")
    ap.add_argument("--cols", "-c", type=int, default=3, help="Grid columns (default: 3)")
    ap.add_argument("--prefix", "-p", default="frame", help="Frame filename prefix (default: frame)")
    args = ap.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        sys.exit(f"Input file not found: {in_path}")

    frames = slice_grid(in_path, Path(args.output), args.rows, args.cols, args.prefix)
    print(f"Successfully sliced {len(frames)} frames into {args.output}/:")
    for f in frames:
        print(f"  {f.name} ({Image.open(f).size[0]}x{Image.open(f).size[1]})")


if __name__ == "__main__":
    main()
